export const brand = {
  name: 'TorqueShed',
  tagline: 'The Garage for Real People',
  shortTagline: 'Real Gearheads. Real Help.',
} as const;

export const emptyStates = {
  garages: {
    title: 'No Garages Yet',
    message: 'Join a garage to start chatting with fellow gearheads.',
    action: 'Browse Garages',
  },
  chat: {
    title: 'No Messages',
    message: 'Be the first to drop some knowledge.',
    action: 'Start the Conversation',
  },
  forums: {
    title: 'No Threads',
    message: 'Got a question or a build to share? Start a thread.',
    action: 'Create Thread',
  },
  vehicles: {
    title: 'Your Garage is Empty',
    message: 'Add your first vehicle to track maintenance and mods.',
    action: 'Add Vehicle',
  },
  notes: {
    title: 'No Notes Yet',
    message: 'Document your work. Your future self will thank you.',
    action: 'Add Note',
  },
  parts: {
    title: 'Find the Right Part',
    message: 'Enter your VIN or select Year/Make/Model to get started.',
    action: 'Search Parts',
  },
  products: {
    title: 'Nothing Trending',
    message: 'Check back soon for hot deals and gear.',
    action: 'Refresh',
  },
  submissions: {
    title: 'No Submissions',
    message: 'Submit a product and earn when it sells.',
    action: 'Submit Product',
  },
  search: {
    title: 'No Results',
    message: 'Try a different search term or filter.',
    action: 'Clear Search',
  },
} as const;

export const microcopy = {
  loading: 'Loading...',
  error: 'Something went wrong. Try again.',
  retry: 'Retry',
  cancel: 'Cancel',
  save: 'Save',
  delete: 'Delete',
  edit: 'Edit',
  confirm: 'Confirm',
  done: 'Done',
  next: 'Next',
  back: 'Back',
  search: 'Search',
  filter: 'Filter',
  sort: 'Sort',
  share: 'Share',
  report: 'Report',
  block: 'Block User',
  post: 'Post',
  reply: 'Reply',
  send: 'Send',
  join: 'Join',
  leave: 'Leave',
  viewAll: 'View All',
  viewDeal: 'View Deal',
  assistMe: 'Assist Me',
  addVehicle: 'Add Vehicle',
  addNote: 'Add Note',
  submitProduct: 'Submit Product',
  online: 'online',
  members: 'members',
  threads: 'threads',
  replies: 'replies',
  hot: 'Hot',
  new: 'New',
  trending: 'Trending',
  justNow: 'Just now',
  minutesAgo: (n: number) => `${n}m ago`,
  hoursAgo: (n: number) => `${n}h ago`,
  daysAgo: (n: number) => `${n}d ago`,
} as const;

export const placeholders = {
  email: 'you@example.com',
  handle: 'gearhead_joe',
  bio: 'Tell us about your builds...',
  location: 'City, State',
  specialties: 'Diesel, Fabrication, Tuning...',
  vin: '1HGBH41JXMN109186',
  year: 'Year',
  make: 'Make',
  model: 'Model',
  nickname: 'Daily Driver',
  noteTitle: 'Oil Change',
  noteContent: 'Describe the work...',
  partName: 'Brake pads, alternator, etc.',
  message: 'Type a message...',
  threadTitle: 'What\'s your question or topic?',
  threadContent: 'Share the details...',
  productTitle: 'Product name',
  productDescription: 'Why is this product great?',
  productPrice: '$99.99',
  affiliateUrl: 'https://amazon.com/dp/...',
} as const;

export const validation = {
  required: 'This field is required',
  email: 'Enter a valid email',
  minLength: (n: number) => `Must be at least ${n} characters`,
  maxLength: (n: number) => `Must be at most ${n} characters`,
  vinFormat: 'Enter a valid 17-character VIN',
  urlFormat: 'Enter a valid URL',
  handleFormat: 'Letters, numbers, and underscores only',
} as const;

export const confirmations = {
  deleteVehicle: 'Delete this vehicle and all its notes?',
  deleteNote: 'Delete this note?',
  deleteMessage: 'Delete this message?',
  deleteThread: 'Delete this thread and all replies?',
  leaveGarage: 'Leave this garage?',
  blockUser: 'Block this user? You won\'t see their content.',
  reportContent: 'Report this content to moderators?',
} as const;
